project:
  type: website

website:
  title: "IS415-Project"
  navbar:
    left:
      - href: "index.qmd"
        text: Home
      - href: "about.qmd"
        text: About
      - href: "project overview/overview.html"
        text: Project Overview

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

