project:
  type: website

website:
  title: "CarSpot"
  navbar:
    left:
      - href: "index.qmd"
        text: Home
      - href: "project overview/overview.html"
        text: Project Overview
      - href: "user_guide/user_guide.html"
        text: App User Guide
      - href: "app/poster.qmd"
        text: Poster

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

