project:
  type: website

website:
  title: "IS415-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: project overview/overview.qmd
        text: Project Overview

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

