project:
  type: website

website:
  title: "CarSpot"
  navbar:
    left:
      - href: "index.qmd"
        text: Home
      - href: "about.qmd"
        text: About
      - href: "project overview/overview.html"
        text: Project Overview

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

